# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1023, 893)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_line = QtWidgets.QLineEdit(Form)
        self.search_line.setMinimumSize(QtCore.QSize(0, 29))
        self.search_line.setStyleSheet("QLineEdit\n"
"{\n"
"\n"
"    border: 2px solid rgb(99, 99, 99);\n"
"font: 10pt\"黑体\";\n"
"\n"
"    background-color: rgb(247, 255, 244);\n"
"\n"
"border - radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background - color: green;\n"
"    color: green\n"
"    border - color: rgb(50, 480, 40);\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"\n"
"}\n"
"\n"
"")
        self.search_line.setObjectName("search_line")
        self.horizontalLayout.addWidget(self.search_line)
        self.search_button = QtWidgets.QPushButton(Form)
        self.search_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"\n"
"\n"
"")
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.page_1)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.instruct_text1 = QtWidgets.QLabel(self.page_1)
        self.instruct_text1.setStyleSheet("font: 75 40pt \"Agency FB\";")
        self.instruct_text1.setAlignment(QtCore.Qt.AlignCenter)
        self.instruct_text1.setObjectName("instruct_text1")
        self.verticalLayout.addWidget(self.instruct_text1)
        self.label_10 = QtWidgets.QLabel(self.page_1)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setStyleSheet("font: 11pt \"黑体\";\n"
"text-decoration: underline;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.movie_select_list = QtWidgets.QListView(self.page_2)
        self.movie_select_list.setStyleSheet("font: 16pt \"黑体\";\n"
"border-color: rgb(155, 157, 255);\n"
"text-decoration: underline;\n"
"border: 2px solid rgb(155, 157, 255);")
        self.movie_select_list.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.movie_select_list.setViewMode(QtWidgets.QListView.ListMode)
        self.movie_select_list.setObjectName("movie_select_list")
        self.verticalLayout_3.addWidget(self.movie_select_list)
        self.instruct_text2 = QtWidgets.QLabel(self.page_2)
        self.instruct_text2.setStyleSheet("font: 18pt \"黑体\";")
        self.instruct_text2.setObjectName("instruct_text2")
        self.verticalLayout_3.addWidget(self.instruct_text2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(135, 0))
        self.label_6.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choice_rank_type_list = QtWidgets.QComboBox(self.page_2)
        self.choice_rank_type_list.setStyleSheet("QComboBox {\n"
"    \n"
"    \n"
"    background-color: rgb(235, 240, 255);\n"
"    border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;  \n"
"    font: 14pt \"黑体\";\n"
"    min-width: 9em;  \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.choice_rank_type_list.setMaxVisibleItems(31)
        self.choice_rank_type_list.setObjectName("choice_rank_type_list")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.choice_rank_type_list.addItem("")
        self.verticalLayout_2.addWidget(self.choice_rank_type_list)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setStyleSheet("font: 16pt \"黑体\";\n"
"")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setMaximumSize(QtCore.QSize(111111, 42))
        self.label_3.setStyleSheet("font: 14pt \"黑体\";\n"
"border-right-color: rgb(7, 7, 7);\n"
"background-color: rgb(255, 248, 230);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.choice_rank_start = QtWidgets.QSpinBox(self.page_2)
        self.choice_rank_start.setEnabled(False)
        self.choice_rank_start.setTabletTracking(False)
        self.choice_rank_start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.choice_rank_start.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.choice_rank_start.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;")
        self.choice_rank_start.setAlignment(QtCore.Qt.AlignCenter)
        self.choice_rank_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.choice_rank_start.setKeyboardTracking(True)
        self.choice_rank_start.setMinimum(1)
        self.choice_rank_start.setMaximum(9999999)
        self.choice_rank_start.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.choice_rank_start.setProperty("value", 1)
        self.choice_rank_start.setObjectName("choice_rank_start")
        self.verticalLayout_2.addWidget(self.choice_rank_start)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 42))
        self.label_4.setMaximumSize(QtCore.QSize(111111, 42))
        self.label_4.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(255, 248, 230);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.choice_rank_finish = QtWidgets.QSpinBox(self.page_2)
        self.choice_rank_finish.setEnabled(False)
        self.choice_rank_finish.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;")
        self.choice_rank_finish.setAlignment(QtCore.Qt.AlignCenter)
        self.choice_rank_finish.setMaximum(64)
        self.choice_rank_finish.setProperty("value", 20)
        self.choice_rank_finish.setObjectName("choice_rank_finish")
        self.verticalLayout_2.addWidget(self.choice_rank_finish)
        self.apply_rank_set_button = QtWidgets.QPushButton(self.page_2)
        self.apply_rank_set_button.setEnabled(False)
        self.apply_rank_set_button.setStyleSheet("QPushButton {\n"
"font: 12pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.apply_rank_set_button.setObjectName("apply_rank_set_button")
        self.verticalLayout_2.addWidget(self.apply_rank_set_button)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.show_back_button = QtWidgets.QPushButton(self.page_2)
        self.show_back_button.setEnabled(False)
        self.show_back_button.setStyleSheet("QPushButton {\n"
"font: 12pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"    color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.show_back_button.setObjectName("show_back_button")
        self.horizontalLayout_2.addWidget(self.show_back_button)
        self.show_next_button = QtWidgets.QPushButton(self.page_2)
        self.show_next_button.setEnabled(False)
        self.show_next_button.setStyleSheet("QPushButton {\n"
"font: 12pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.show_next_button.setObjectName("show_next_button")
        self.horizontalLayout_2.addWidget(self.show_next_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 400))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.back_to_page2_button = QtWidgets.QPushButton(self.page_3)
        self.back_to_page2_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.back_to_page2_button.setObjectName("back_to_page2_button")
        self.verticalLayout_5.addWidget(self.back_to_page2_button)
        self.movie_name = QtWidgets.QLabel(self.page_3)
        self.movie_name.setStyleSheet("\n"
"\n"
"font: 24pt \"黑体\";\n"
"")
        self.movie_name.setAlignment(QtCore.Qt.AlignCenter)
        self.movie_name.setObjectName("movie_name")
        self.verticalLayout_5.addWidget(self.movie_name)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.movie_image = QtWidgets.QLabel(self.page_3)
        self.movie_image.setMinimumSize(QtCore.QSize(230, 270))
        self.movie_image.setText("")
        self.movie_image.setObjectName("movie_image")
        self.gridLayout_3.addWidget(self.movie_image, 0, 0, 1, 1)
        self.movie_info_cmts = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movie_info_cmts.sizePolicy().hasHeightForWidth())
        self.movie_info_cmts.setSizePolicy(sizePolicy)
        self.movie_info_cmts.setMinimumSize(QtCore.QSize(225, 0))
        self.movie_info_cmts.setStyleSheet("font: 17pt \"黑体\";")
        self.movie_info_cmts.setWordWrap(True)
        self.movie_info_cmts.setObjectName("movie_info_cmts")
        self.gridLayout_3.addWidget(self.movie_info_cmts, 0, 1, 1, 1)
        self.watch_video_button = QtWidgets.QPushButton(self.page_3)
        self.watch_video_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"")
        self.watch_video_button.setObjectName("watch_video_button")
        self.gridLayout_3.addWidget(self.watch_video_button, 1, 0, 1, 1)
        self.cmts_rate_button = QtWidgets.QPushButton(self.page_3)
        self.cmts_rate_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.cmts_rate_button.setObjectName("cmts_rate_button")
        self.gridLayout_3.addWidget(self.cmts_rate_button, 1, 1, 1, 1)
        self.see_cmts_button = QtWidgets.QPushButton(self.page_3)
        self.see_cmts_button.setEnabled(True)
        self.see_cmts_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.see_cmts_button.setObjectName("see_cmts_button")
        self.gridLayout_3.addWidget(self.see_cmts_button, 2, 0, 1, 1)
        self.open_in_browser_button = QtWidgets.QPushButton(self.page_3)
        self.open_in_browser_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.open_in_browser_button.setObjectName("open_in_browser_button")
        self.gridLayout_3.addWidget(self.open_in_browser_button, 2, 1, 1, 1)
        self.word_cloud_box = QtWidgets.QComboBox(self.page_3)
        self.word_cloud_box.setStyleSheet("QComboBox{font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;}\n"
"QComboBox:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);}")
        self.word_cloud_box.setObjectName("word_cloud_box")
        self.word_cloud_box.addItem("")
        self.word_cloud_box.addItem("")
        self.word_cloud_box.addItem("")
        self.gridLayout_3.addWidget(self.word_cloud_box, 3, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 3)
        self.movie_info_main = QtWidgets.QTextBrowser(self.page_3)
        self.movie_info_main.setStyleSheet("background-color: rgb(255, 248, 255);\n"
"font: 14pt \"黑体\";\n"
"border: 2px solid rgb(155, 157, 255);\n"
"")
        self.movie_info_main.setObjectName("movie_info_main")
        self.gridLayout_4.addWidget(self.movie_info_main, 1, 3, 4, 1)
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 3)
        self.user_words_add_line = QtWidgets.QLineEdit(self.page_3)
        self.user_words_add_line.setMinimumSize(QtCore.QSize(0, 45))
        self.user_words_add_line.setStyleSheet("border: 2px solid rgb(99, 99, 99);\n"
"font: 14pt\"黑体\";\n"
"background-color: rgb(247, 255, 244);\n"
"border - radius: 6px;")
        self.user_words_add_line.setObjectName("user_words_add_line")
        self.gridLayout_4.addWidget(self.user_words_add_line, 3, 0, 1, 3)
        self.clear_user_words_button = QtWidgets.QPushButton(self.page_3)
        self.clear_user_words_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.clear_user_words_button.setObjectName("clear_user_words_button")
        self.gridLayout_4.addWidget(self.clear_user_words_button, 4, 0, 1, 1)
        self.add_button = QtWidgets.QPushButton(self.page_3)
        self.add_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.add_button.setObjectName("add_button")
        self.gridLayout_4.addWidget(self.add_button, 4, 1, 1, 1)
        self.add_finish_button = QtWidgets.QPushButton(self.page_3)
        self.add_finish_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.add_finish_button.setObjectName("add_finish_button")
        self.gridLayout_4.addWidget(self.add_finish_button, 4, 2, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(self.page_3)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout_4.addWidget(self.progress_bar, 5, 0, 1, 4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.back_to_page3_button = QtWidgets.QPushButton(self.page_4)
        self.back_to_page3_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.back_to_page3_button.setObjectName("back_to_page3_button")
        self.verticalLayout_6.addWidget(self.back_to_page3_button)
        self.word_cloud_img = QtWidgets.QLabel(self.page_4)
        self.word_cloud_img.setObjectName("word_cloud_img")
        self.verticalLayout_6.addWidget(self.word_cloud_img)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.back_to_page4_button = QtWidgets.QPushButton(self.page_5)
        self.back_to_page4_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.back_to_page4_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.back_to_page4_button.setObjectName("back_to_page4_button")
        self.gridLayout_9.addWidget(self.back_to_page4_button, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_5)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.mpl_img = QtWidgets.QGridLayout()
        self.mpl_img.setObjectName("mpl_img")
        self.gridLayout_15.addLayout(self.mpl_img, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 1, 0, 1, 1)
        self.choice_mpl_style = QtWidgets.QComboBox(self.page_5)
        self.choice_mpl_style.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.choice_mpl_style.setStyleSheet("QComboBox {\n"
"    background-color: rgb(251, 248, 255);\n"
"    border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;  \n"
"    font: 14pt \"黑体\";\n"
"    min-width: 9em;  \n"
"}")
        self.choice_mpl_style.setObjectName("choice_mpl_style")
        self.choice_mpl_style.addItem("")
        self.choice_mpl_style.addItem("")
        self.choice_mpl_style.addItem("")
        self.choice_mpl_style.addItem("")
        self.gridLayout_9.addWidget(self.choice_mpl_style, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.back_button = QtWidgets.QPushButton(self.page_6)
        self.back_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.gridLayout_6.addWidget(self.back_button, 1, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.page_6)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("font: 14pt \"黑体\";")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.page_6)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.which_page_button = QtWidgets.QSpinBox(self.page_6)
        self.which_page_button.setStyleSheet("font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;")
        self.which_page_button.setMinimum(1)
        self.which_page_button.setMaximum(256)
        self.which_page_button.setObjectName("which_page_button")
        self.gridLayout_6.addWidget(self.which_page_button, 4, 2, 1, 2)
        self.cmts_box = QtWidgets.QTextBrowser(self.page_6)
        self.cmts_box.setStyleSheet("font: 12pt \"黑体\";\n"
"background-color: rgb(246, 252, 255);\n"
"border: 2px solid rgb(155, 157, 255);")
        self.cmts_box.setObjectName("cmts_box")
        self.gridLayout_6.addWidget(self.cmts_box, 2, 0, 1, 4)
        self.go_page3_button = QtWidgets.QPushButton(self.page_6)
        self.go_page3_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.go_page3_button.setObjectName("go_page3_button")
        self.gridLayout_6.addWidget(self.go_page3_button, 0, 0, 1, 4)
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 3, 1, 1)
        self.next_button = QtWidgets.QPushButton(self.page_6)
        self.next_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.next_button.setObjectName("next_button")
        self.gridLayout_6.addWidget(self.next_button, 3, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 3, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.back_video_to_page3_button = QtWidgets.QPushButton(self.page_7)
        self.back_video_to_page3_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.back_video_to_page3_button.setObjectName("back_video_to_page3_button")
        self.verticalLayout_7.addWidget(self.back_video_to_page3_button)
        self.choice_pre_video_button = QtWidgets.QComboBox(self.page_7)
        self.choice_pre_video_button.setStyleSheet("QComboBox {\n"
"    background-color: rgb(251, 248, 255);\n"
"    border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;  \n"
"    font: 14pt \"黑体\";\n"
"    min-width: 9em;  \n"
"}")
        self.choice_pre_video_button.setObjectName("choice_pre_video_button")
        self.choice_pre_video_button.addItem("")
        self.choice_pre_video_button.addItem("")
        self.choice_pre_video_button.setItemText(1, "")
        self.verticalLayout_7.addWidget(self.choice_pre_video_button)
        self.player_window = QVideoWidget(self.page_7)
        self.player_window.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.player_window.setObjectName("player_window")
        self.verticalLayout_7.addWidget(self.player_window)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 0, 0, 1, 3)
        self.pause_button = QtWidgets.QPushButton(self.page_7)
        self.pause_button.setEnabled(False)
        self.pause_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.pause_button.setObjectName("pause_button")
        self.gridLayout_5.addWidget(self.pause_button, 1, 0, 1, 1)
        self.play_button = QtWidgets.QPushButton(self.page_7)
        self.play_button.setEnabled(False)
        self.play_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.play_button.setObjectName("play_button")
        self.gridLayout_5.addWidget(self.play_button, 1, 1, 1, 1)
        self.continue_button = QtWidgets.QPushButton(self.page_7)
        self.continue_button.setEnabled(False)
        self.continue_button.setStyleSheet("QPushButton {\n"
"font: 14pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(212, 217, 220);\n"
"}")
        self.continue_button.setObjectName("continue_button")
        self.gridLayout_5.addWidget(self.continue_button, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.search_button.clicked.connect(Form.go_page2_search)
        self.movie_select_list.doubleClicked['QModelIndex'].connect(Form.go_page3_movie_analyze)
        self.back_to_page2_button.clicked.connect(Form.go_current_page2)
        self.back_to_page3_button.clicked.connect(Form.back_wordcloud_to_page3)
        self.cmts_rate_button.clicked['bool'].connect(Form.cmts_rate_show)
        self.back_to_page4_button.clicked.connect(Form.back_mpl_to_page3)
        self.choice_mpl_style.currentIndexChanged['int'].connect(Form.cmts_rate_show_changed)
        self.search_line.returnPressed.connect(Form.go_page2_search)
        self.choice_rank_type_list.currentIndexChanged['int'].connect(Form.set_choice_rank)
        self.see_cmts_button.clicked.connect(Form.set_short_cmts)
        self.back_button.clicked.connect(Form.previous_cmts_page)
        self.next_button.clicked.connect(Form.next_cmts_page)
        self.which_page_button.editingFinished.connect(Form.choice_cmts_page)
        self.go_page3_button.clicked.connect(Form.back_cmts_to_page3)
        self.open_in_browser_button.clicked.connect(Form.open_in_browser)
        self.apply_rank_set_button.clicked.connect(Form.set_choice_rank)
        self.show_next_button.clicked.connect(Form.set_choice_rank_next)
        self.show_back_button.clicked.connect(Form.set_choice_rank_back)
        self.play_button.clicked.connect(Form.pre_video_play)
        self.watch_video_button.clicked.connect(Form.go_page7_pre_video_show)
        self.choice_pre_video_button.currentIndexChanged['int'].connect(Form.choice_pre_video)
        self.back_video_to_page3_button.clicked.connect(Form.back_video_to_page3)
        self.pause_button.clicked.connect(Form.pre_video_pause)
        self.continue_button.clicked.connect(Form.pre_video_continue)
        self.word_cloud_box.currentIndexChanged['int'].connect(Form.word_cloud_choice)
        self.user_words_add_line.returnPressed.connect(Form.add_user_words)
        self.add_button.clicked.connect(Form.add_user_words)
        self.add_finish_button.clicked.connect(Form.finish_user_words)
        self.clear_user_words_button.clicked.connect(Form.clear_user_words)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "豆瓣电影简易工具"))
        self.search_button.setText(_translate("Form", "搜索"))
        self.instruct_text1.setText(_translate("Form", "搜点电影吧👆"))
        self.label.setText(_translate("Form", "这个没啥用的程序由杭州电子科技大学管理学院大一新生-陈笛编写"))
        self.instruct_text2.setText(_translate("Form", "双击选择一部你感兴趣的电影吧🧐"))
        self.choice_rank_type_list.setItemText(0, _translate("Form", "【实时榜单】："))
        self.choice_rank_type_list.setItemText(1, _translate("Form", "新片榜"))
        self.choice_rank_type_list.setItemText(2, _translate("Form", "一周口碑榜"))
        self.choice_rank_type_list.setItemText(3, _translate("Form", "北美票房榜"))
        self.choice_rank_type_list.setItemText(4, _translate("Form", "【分类排行榜】："))
        self.choice_rank_type_list.setItemText(5, _translate("Form", "剧情"))
        self.choice_rank_type_list.setItemText(6, _translate("Form", "喜剧"))
        self.choice_rank_type_list.setItemText(7, _translate("Form", "动作"))
        self.choice_rank_type_list.setItemText(8, _translate("Form", "爱情"))
        self.choice_rank_type_list.setItemText(9, _translate("Form", "科幻"))
        self.choice_rank_type_list.setItemText(10, _translate("Form", "动画"))
        self.choice_rank_type_list.setItemText(11, _translate("Form", "悬疑"))
        self.choice_rank_type_list.setItemText(12, _translate("Form", "惊悚"))
        self.choice_rank_type_list.setItemText(13, _translate("Form", "恐怖"))
        self.choice_rank_type_list.setItemText(14, _translate("Form", "纪录片"))
        self.choice_rank_type_list.setItemText(15, _translate("Form", "短片"))
        self.choice_rank_type_list.setItemText(16, _translate("Form", "情色"))
        self.choice_rank_type_list.setItemText(17, _translate("Form", "同性"))
        self.choice_rank_type_list.setItemText(18, _translate("Form", "音乐"))
        self.choice_rank_type_list.setItemText(19, _translate("Form", "歌舞"))
        self.choice_rank_type_list.setItemText(20, _translate("Form", "家庭"))
        self.choice_rank_type_list.setItemText(21, _translate("Form", "儿童"))
        self.choice_rank_type_list.setItemText(22, _translate("Form", "传记"))
        self.choice_rank_type_list.setItemText(23, _translate("Form", "历史"))
        self.choice_rank_type_list.setItemText(24, _translate("Form", "战争"))
        self.choice_rank_type_list.setItemText(25, _translate("Form", "犯罪"))
        self.choice_rank_type_list.setItemText(26, _translate("Form", "西部"))
        self.choice_rank_type_list.setItemText(27, _translate("Form", "奇幻"))
        self.choice_rank_type_list.setItemText(28, _translate("Form", "冒险"))
        self.choice_rank_type_list.setItemText(29, _translate("Form", "灾难"))
        self.choice_rank_type_list.setItemText(30, _translate("Form", "武侠"))
        self.choice_rank_type_list.setItemText(31, _translate("Form", "古装"))
        self.choice_rank_type_list.setItemText(32, _translate("Form", "运动"))
        self.choice_rank_type_list.setItemText(33, _translate("Form", "黑色电影"))
        self.label_2.setText(_translate("Form", "可以在这选择一个排行榜👆"))
        self.label_3.setText(_translate("Form", "排名开始位置"))
        self.label_4.setText(_translate("Form", "电影数(64MAX)"))
        self.apply_rank_set_button.setText(_translate("Form", "应用设置"))
        self.show_back_button.setText(_translate("Form", "上一页"))
        self.show_next_button.setText(_translate("Form", "下一页"))
        self.back_to_page2_button.setText(_translate("Form", "返回"))
        self.movie_name.setText(_translate("Form", "TextLabel"))
        self.movie_info_cmts.setText(_translate("Form", "TextLabel"))
        self.watch_video_button.setText(_translate("Form", "观看预告片"))
        self.cmts_rate_button.setText(_translate("Form", "评价星级可视化"))
        self.see_cmts_button.setText(_translate("Form", "查看短评"))
        self.open_in_browser_button.setText(_translate("Form", "在浏览器中打开"))
        self.word_cloud_box.setItemText(0, _translate("Form", "词云分析"))
        self.word_cloud_box.setItemText(1, _translate("Form", "默认版(默认处理)"))
        self.word_cloud_box.setItemText(2, _translate("Form", "自定义版(额外处理)"))
        self.user_words_add_line.setText(_translate("Form", "请在此处添加不显示的词语"))
        self.clear_user_words_button.setText(_translate("Form", "清除已添加"))
        self.add_button.setText(_translate("Form", "添加"))
        self.add_finish_button.setText(_translate("Form", "结束添加"))
        self.back_to_page3_button.setText(_translate("Form", "返回"))
        self.word_cloud_img.setText(_translate("Form", "TextLabel"))
        self.back_to_page4_button.setText(_translate("Form", "返回"))
        self.choice_mpl_style.setItemText(0, _translate("Form", "折线图(默认)"))
        self.choice_mpl_style.setItemText(1, _translate("Form", "散点图"))
        self.choice_mpl_style.setItemText(2, _translate("Form", "柱状图"))
        self.choice_mpl_style.setItemText(3, _translate("Form", "饼状图"))
        self.back_button.setText(_translate("Form", "上一页"))
        self.label_9.setText(_translate("Form", "选择一页"))
        self.go_page3_button.setText(_translate("Form", "返回"))
        self.next_button.setText(_translate("Form", "下一页"))
        self.back_video_to_page3_button.setText(_translate("Form", "返回"))
        self.choice_pre_video_button.setItemText(0, _translate("Form", "选择一部预告"))
        self.pause_button.setText(_translate("Form", "暂停"))
        self.play_button.setText(_translate("Form", "播放"))
        self.continue_button.setText(_translate("Form", "继续"))

